spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_database;MODE=MariaDB
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    sql:
      init:
        mode: always


  flyway:
    enabled: false




logging.level:
  root: error
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace


jwt:
  secret:
    key: "yourTestSecretKeyMustBeLongEnoughForHS256Algorithm"
  access-token:
    expire-time: 6000000   # 10분
  refresh-token:
    expire-time: 86400000 # 24시간


stomp-connect-url: "/test/ws-stomp"